CREATE TABLE Jobs (
	Job_ID varchar(3) PRIMARY KEY NOT NULL,
	Staff_Job TEXT NOT NULL,
	Staff_Salary INTEGER NOT NULL
	
)

CREATE TABLE Staff (
	Staff_ID VARCHAR(5) PRIMARY KEY NOT NULL,
	Staff_FName TEXT NOT NULL,
	Staff_MName TEXT,
	Staff_LName TEXT NOT NULL,
	Password VARCHAR(15) NOT NULL,
	Job_ID VARCHAR(3) NOT NULL,
	FOREIGN KEY (Job_ID) REFERENCES Jobs(Job_ID) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Patients (
	Patient_ID VARCHAR(6) PRIMARY KEY NOT NULL,
	Patient_FName TEXT NOT NULL,
	Patient_MName TEXT,
	Patient_LName TEXT NOT NULL,
	Patient_Sex VARCHAR(1) NOT NULL, 
	Patient_DOB TEXT NOT NULL,
	Patient_TeleNO NUMERIC NOT NULL,
	Patient_Email TEXT NOT NULL
)

CREATE TABLE Notes (
	Note_ID	INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Note_Date	TEXT NOT NULL,
	Note	TEXT NOT NULL,
	Patient_ID	VARCHAR(6) NOT NULL,
	Staff_ID	TEXT NOT NULL,
	FOREIGN KEY(Patient_ID) REFERENCES Patients(Patient_ID) ON DELETE CASCADE ON UPDATE CASCADE
	FOREIGN KEY(Staff_ID) REFERENCES Staff(Staff_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Appointments (
	Patient_ID VARCHAR(6) NOT NULL,
	Staff_ID VARCHAR(5) NOT NULL,
	App_Date TEXT NOT NULL,
	App_Time TEXT NOT NULL,
	FOREIGN KEY (Patient_ID) REFERENCES Patients(Patient_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Staff_ID) REFERENCES Staff(Staff_ID) ON DELETE CASCADE ON UPDATE CASCADE
)
	
	
	